/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaexperto;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import sistemaexperto.Entidad.BC;
import sistemaexperto.Entidad.Hecho;
import sistemaexperto.Entidad.Literal;
import sistemaexperto.Entidad.Regla;
import sistemaexperto.util.GV;
import sistemaexperto.util.listenerBC;
import sistemaexperto.util.listenerRegla;

/**
 *
 * @author Lion
 */
public class JPRegla extends javax.swing.JPanel implements listenerRegla{

    /**
     * Creates new form JPRegla
     */
    Object selected;
    private DefaultListModel dListModel;
    private int endLiteral;//Posicion de "Enconces" en la lista;
    private Regla regla;
    private listenerBC mListenerBc;
    public JPRegla() {
        initComponents();
        endLiteral=1;
        this.dListModel=new DefaultListModel();
        this.dListModel.addElement("Si");
        this.dListModel.addElement("Entonces");
        this.jLregla.setModel(dListModel);
        this.jLregla.updateUI();
        regla=new Regla();
        this.jLregla.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()){
                    selected =((JList)e.getSource())
                            .getSelectedValue();
                }
            }
        });
    }

    public listenerBC getmListenerBc() {
        return mListenerBc;
    }

    public void setmListenerBc(listenerBC mListenerBc) {
        this.mListenerBc = mListenerBc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void setRegla(Regla regla){
        this.regla=regla;
        this.regla.getPremisa();
        for (Literal literal : this.regla.getPremisa()) {
            this.dListModel.add(this.endLiteral, literal);
        }
        this.dListModel.addElement(this.regla.getConclusion());
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLPremisa = new javax.swing.JScrollPane();
        jLregla = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jBincluir = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(462, 267));
        setPreferredSize(new java.awt.Dimension(462, 267));
        setLayout(new java.awt.BorderLayout());

        jLregla.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Si", "Entonces" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jLPremisa.setViewportView(jLregla);

        add(jLPremisa, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jBincluir.setText("Agregar");
        jBincluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBincluirActionPerformed(evt);
            }
        });
        jPanel1.add(jBincluir);

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jBEliminar);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents
    private JFEditarRegla editarRegla;
    private void jBincluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBincluirActionPerformed
        // TODO add your handling code here:
        if(GV.tablaVar!=null && GV.tablaVar.getLista()!=null && GV.tablaVar.getLista().size()>0){
            if(selected instanceof String && ((String)selected).equals("Si")){
                //TODO Agrega un literal
                editarRegla= new JFEditarRegla(false);
                editarRegla.setListenerRegla(this);
                editarRegla.setVisible(true);
            }else if(selected instanceof String && ((String)selected).equals("Entonces")){
                //TODO Agrega un hecho
                editarRegla= new JFEditarRegla(true); 
                editarRegla.setListenerRegla(this);
                editarRegla.setVisible(true);
            }
           
        }else
            JOptionPane.showMessageDialog(this, "No hay variables para crear reglas");
    }//GEN-LAST:event_jBincluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        if(GV.tableBC==null)
//            GV.tableBC=new BC();
//        GV.tableBC.addRegla(regla);
        if(this.mListenerBc!=null && regla!=null)
            this.mListenerBc.addRegla(regla);
            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        // TODO add your handling code here:
        if(selected!=null){
            int indexS=this.dListModel.indexOf(selected);
            if(indexS>0 && indexS<this.endLiteral)
            {
                this.dListModel.removeElement(selected);
                this.endLiteral--;
                this.regla.getPremisa().remove(selected);
                this.jLregla.updateUI();
            }
            if(indexS==this.endLiteral+1){
                this.dListModel.remove(indexS);
                this.regla.setConclusion(null);
                this.jLregla.updateUI();
            }
        }
    }//GEN-LAST:event_jBEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBincluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jLPremisa;
    private javax.swing.JList jLregla;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addLiteral(Literal l) {
        if(l!=null){
            this.regla.addLiteralToRegla(l);
            this.dListModel.add(this.endLiteral, l);
            this.endLiteral++;
        }
    }

    @Override
    public void addHehco(Hecho hecho) {
        if(hecho!=null)
        {
            if(this.regla.getConclusion()==null )
            {
                this.dListModel.addElement(hecho);
                this.regla.setConclusion(hecho);
            }
            else{
                this.dListModel.removeElement(this.regla.getConclusion());
                this.dListModel.addElement(hecho);
                this.regla.setConclusion(hecho);
            }
            this.updateUI();
            
            
        }
    }
}
